DefaultContentLanguage = "en"
author = "Martin"
baseURL = "https://stu-stu.studio"
copyright = "Copyright © 2020 Martin"
date = 2020-11-27T18:50:24Z
description = "This is a page where I write about things."
enableInlineShortcodes = true
feature_image = "/images/73eeec07-f1fd-485d-bd4d-5cb24d9cc855-2020-11-27.jpeg"
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
tags = []
theme = "github.com/jonathanjanssens/hugo-casper3"
title = "Just stuff."
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1
[params]
description = "Stuff and tech. And tech stuff."
logo = "/images/9CE62F6C-BE02-4DF2-B2E4-7BC933338901.png"
mainSections = ["post"]
twitter = "https://twitter.com"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
